sonar.organization=eigensu
sonar.projectKey=Eigensu_first-layout

sonar.sources=apps/frontend/src,apps/backend/app
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc
sonar.tests=apps/backend/tests
sonar.test.inclusions=apps/frontend/src/**/*.test.ts,apps/frontend/src/**/*.test.tsx
sonar.python.coverage.reportPaths=apps/backend/coverage.xml
sonar.javascript.lcov.reportPaths=apps/frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=apps/frontend/coverage/lcov.info

sonar.python.version=3.13
