sonar.organization=eigensu
sonar.projectKey=Eigensu_first-layout

sonar.sources=apps/frontend/src,apps/backend/app
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.11
